package(default_visibility = ["//visibility:public"])

cc_library(
    name = "version",
    includes = ["include"],
    srcs = glob([
        "include/*.h",
        "src/*.cc",
        "src/*.h",
    ]),
    copts = [
        "-Werror",
    ],
)
