

cc_binary(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        # "//mwal:mwal",
    ],
    copts = []
)

cc_binary(
    name = "test_smp",
    srcs = ["test_smp.cc"],
    deps = [
        # "//mwal:mwal",
    ],
    copts = []
)

# cc_binary(
#     name = "test",
#     srcs = ["test.cc", "util.h"],
#     deps = [
#         "//mwal:mwal",
#     ],
#     copts = []
# )