package(default_visibility = ["//visibility:public"])

cc_library(
    name = "util",
    srcs = glob([
        "*.h",
        "*.cc",
    ]),
    copts = [
        "-Werror",
        "-Wall"
        # "-Wno-sign-compare",
        # "-Wno-error=format"
    ],
    deps = [
    ],
)
